name: swapify
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  carousel_slider: ^5.0.0
  cloud_firestore: ^5.5.1
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dotenv: ^4.2.0
  equatable: ^2.0.7
  firebase_auth: ^5.3.4
  firebase_cloud_messaging_flutter: ^1.0.6
  firebase_core: ^3.8.1
  firebase_database: ^11.2.0
  firebase_messaging: ^15.2.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_launcher_icons: ^0.14.3
  flutter_localizations:
    sdk: flutter
  flutter_map: ^7.0.2
  geocoding: ^2.0.0
  geolocator: ^9.0.2
  get_it: ^8.0.2
  givestarreviews: ^1.0.2
  go_router: ^14.6.2
  google_fonts: ^4.0.4
  google_maps_flutter: ^2.10.0
  google_sign_in: ^6.2.2
  http: ^1.2.2
  image_picker: ^1.1.2
  intl: ^0.19.0
  latlong2: ^0.9.1
  mobile_scanner: ^3.0.0
  permission_handler: ^11.3.0
  shared_preferences: ^2.3.3
  flutter_rating_bar: ^4.0.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.3
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/logos/
    - assets/images/
    - .env

flutter_native_splash:
  color: "#ffffff"
  image: assets/logos/logo_fin.png
  android: true
  ios: true
  web: true

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logos/logo_app.png"
  remove_alpha_ios: true
