name: swapify
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  cloud_firestore: ^5.5.1
  cupertino_icons: ^1.0.2
  firebase_auth: ^5.3.4
  flutter:
    sdk: flutter
  get_it: ^8.0.2
  google_fonts: ^5.1.0
  http: ^1.2.2

dev_dependencies:
  dartz: ^0.10.1
  dotenv: ^4.2.0
  equatable: ^2.0.7
  firebase_core: ^3.8.1
  firebase_database: ^11.2.0
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.2.1
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.3
  flutter_test:
    sdk: flutter
  go_router: ^14.6.2
  google_sign_in: ^6.2.2
  image_picker: ^1.1.2
  shared_preferences: ^2.3.3

flutter:
  uses-material-design: true
  assets:
    - assets/logos/
    - assets/images/
    - .env

flutter_native_splash:
  color: "#ffffff"
  image: assets/logos/logo_fin.png
  android: true
  ios: true
  web: true
